version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: local_dev_postgres
    restart: always
    ports:
      - "9632:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local_dev_backend
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  local_dev_network:
